package com.zero.address.domain.response;

import java.io.Serializable;

/**
 * Country视图对象
 * @date 2018年1月17日 下午11:42:38
 * @author zero
 */
public class CountryVo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 910554226338517625L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column country.code
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	private String code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column country.name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column country.alia_name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	private String aliaName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column country.english_name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	private String englishName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column country.code
	 *
	 * @return the value of country.code
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column country.code
	 *
	 * @param code
	 *            the value for country.code
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column country.name
	 *
	 * @return the value of country.name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column country.name
	 *
	 * @param name
	 *            the value for country.name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column country.alia_name
	 *
	 * @return the value of country.alia_name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public String getAliaName() {
		return aliaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column country.alia_name
	 *
	 * @param aliaName
	 *            the value for country.alia_name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public void setAliaName(String aliaName) {
		this.aliaName = aliaName == null ? null : aliaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column country.english_name
	 *
	 * @return the value of country.english_name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column country.english_name
	 *
	 * @param englishName
	 *            the value for country.english_name
	 *
	 * @mbg.generated Wed Jan 17 23:18:46 CST 2018
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName == null ? null : englishName.trim();
	}

}
