package com.zero.address.dao.entity;

import java.io.Serializable;

public class Area implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_code
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.name
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.alia_name
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private String aliaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.parent_code
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.level
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.type
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_code
     *
     * @return the value of area.area_code
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_code
     *
     * @param areaCode the value for area.area_code
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.name
     *
     * @return the value of area.name
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.name
     *
     * @param name the value for area.name
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.alia_name
     *
     * @return the value of area.alia_name
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public String getAliaName() {
        return aliaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.alia_name
     *
     * @param aliaName the value for area.alia_name
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setAliaName(String aliaName) {
        this.aliaName = aliaName == null ? null : aliaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.parent_code
     *
     * @return the value of area.parent_code
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.parent_code
     *
     * @param parentCode the value for area.parent_code
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.level
     *
     * @return the value of area.level
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.level
     *
     * @param level the value for area.level
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.type
     *
     * @return the value of area.type
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.type
     *
     * @param type the value for area.type
     *
     * @mbg.generated Wed Jan 10 00:14:39 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }
}